# Generated by Django 2.0.1 on 2018-06-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
